// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcCkMmNlRQMcSpfz1e5tHYYKZb-gKDBJU',
    appId: '1:109533872827:web:379e6e086c6065cf845f9e',
    messagingSenderId: '109533872827',
    projectId: 'capstone-dream',
    authDomain: 'capstone-dream.firebaseapp.com',
    storageBucket: 'capstone-dream.appspot.com',
    measurementId: 'G-FFNPFK8M89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY4aXyliJ_qTZWIJFTf0DUlnH9QdXhdTg',
    appId: '1:109533872827:android:df27abed6eb3ccd9845f9e',
    messagingSenderId: '109533872827',
    projectId: 'capstone-dream',
    storageBucket: 'capstone-dream.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQwdtvxf6RuIrLgkEI1zoNV1ejPYTzs8o',
    appId: '1:109533872827:ios:44bdc6672f1e2072845f9e',
    messagingSenderId: '109533872827',
    projectId: 'capstone-dream',
    storageBucket: 'capstone-dream.appspot.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQwdtvxf6RuIrLgkEI1zoNV1ejPYTzs8o',
    appId: '1:109533872827:ios:319c5cdb61d807d3845f9e',
    messagingSenderId: '109533872827',
    projectId: 'capstone-dream',
    storageBucket: 'capstone-dream.appspot.com',
    iosBundleId: 'com.example.capstone.RunnerTests',
  );
}
